# Generated by Django 3.2.3 on 2021-06-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(related_name='patients', to='reservation.Doctor'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
